### ISSUE TITLE
.env

### ISSUE THREAD

**Issue by izac3d** [dnicerio/mern-todolist#1]
Hi
Can you put example for .env for local testing ?

**Comment by dnicerio** [comment]
> Hi
> Can you put example for .env for local testing ?

sorry I used mongodb atlas for this app. not familiar yet in setting up a local mongodb database but this is the only content of this app's .env

DATABASE_URL=mongodb+srv://<userid>:<password>@<cluster-link>/<database-name>?retryWrites=true&w=majority

**Comment by izac3d** [comment]
thanks I figure it out and very nice work

**Comment by dnicerio** [comment]
thanks man
